### ISSUE TITLE
Capture `screenshot` events

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/ipfs-station#29]
with http://electron.atom.io/docs/v0.30.0/api/global-shortcut/

**Comment by jbenet** [comment]
:camera: :city_sunset: :+1:

**Comment by whyrusleeping** [comment]
that seems sketchy to me..

**Comment by jbenet** [comment]
> that seems sketchy to me..

why?

**Comment by whyrusleeping** [comment]
we're going to capture every single screenshot someone takes on their computer? maybe as like an extreme multiclick opt in... but otherwise that seems a bit invasive.

**Comment by diasdavid** [comment]
@whyrusleeping other apps are currently doing that, as an `opt-in` of course. We can have a special keyboard shortcut for ipfs screenshots, but capturing the natural events from the events is more convenient to the user (+ Mac OS screenshots are really cool)

**Comment by jbenet** [comment]
> we're going to capture every single screenshot someone takes on their computer?

oh what, somehow i missed that. @diasdavid i think that's pretty sketchy. we can allow the user to change the key combinations, and they can set that up. i think that's how Skitch and friends work?

**Comment by diasdavid** [comment]
Well, cloudapp, couldup and dropbox capture everything. Custom keyboard shortcut is fine too

**Comment by Dignifiedquire** [comment]
I suggest that by default we capture all screenshots and add a setting where one can disable it.

**Comment by diasdavid** [comment]
I like that @Dignifiedquire :)

**Comment by bcomnes** [comment]
Anyone know how this will interact with other apps capturing screenshots?  Dropbox comes to mind.

**Comment by jbenet** [comment]
> > I suggest that by default we capture all screenshots and add a setting where one can disable it.
>
> I like that @Dignifiedquire :)

i really don't. @whyrusleeping is right -- this is a privacy problem. I think we should do what many other apps do and create a shortcut that you can use (separate), but which you can rebind to override your normal one. That way the user is in control.

eg i have https://github.com/jbenet/ipfs-screencap bound to `CMD+SHIFT+2` on OSX

**Comment by Dignifiedquire** [comment]
There is an open PR on electron to make this a whole lot easier: https://github.com/atom/electron/pull/2963 so I suggest we wait for that to be merged.

**Comment by hacdias** [comment]
What's the state of this issue? Is this feature still wanted? 😄

**Comment by diasdavid** [comment]
It should not be enabled by default and if enabled, it should let the user pick a custom key shortcut for it to activate.

**Comment by hacdias** [comment]
Done on #562. The shortcut cmd/ctrl+alt+s is always enabled. Should there be an option to activate/deactivate?

**Comment by lidel** [comment]
Yes, there should be an UI for changing or at least deactivating keyboard shortcuts, otherwise we will make random people sangry (sad+angry 🙃).

(tl;dr will now commence)

When it comes to shortcuts, it is very likely we will run into problems on different platforms / machines.

Combinations that are unused on linux/macOS may be hijacked by default on MS Windows (example: https://github.com/lidel/google-music-hotkeys/issues/3#issuecomment-352142246) or even by some third party app that "user been running for past 5 years and don't want to change established habits".

A good place too look at for prior-work is the browser extension ecosystem, which had to tackle the same problem, being OS-agnostic. WebExtensions can define keyboard shortcuts as [`commands` in `manifest.info`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands) in a platform-specific way:
```js
"commands": {
  "toggle-feature": {
    "suggested_key": {
      "default": "Alt+Shift+U",
      "linux": "Ctrl+Shift+U"
    },
    "description": "Send a 'toggle-feature' event to the extension"
  },
  "do-another-thing": {
    "suggested_key": {
      "default": "Ctrl+Shift+Y"
    }
  }
}
```

On top of that, Google Chrome provides [UI for customizing shortcuts](https://user-images.githubusercontent.com/157609/33337860-a03f29f6-d474-11e7-88b9-748739b20725.gif)
Worth noting that [Firefox does not provide UI yet](https://bugzilla.mozilla.org/show_bug.cgi?id=1303384), so user has no choice but to use defaults from `manifest.info`, thich means developer should be extra conscious about which key combination is picked.

**Comment by hacdias** [comment]
@lidel unfortunately, Electron doesn't have a way to add different default shortcodes for each operating system. And even when we add a shortcut, it may fail silently if there is already another shortcut with those keys. This way, I cannot know if there is some program already using that shortcut.

Right now I'm only letting the user enable/disable `CTRL/CMD+ALT+S` for the screenshot. In the future I'll add the option to edit the letter. 😄 What do you think?

**Comment by lidel** [comment]
Yup, sounds good 👍
