### ISSUE TITLE
feat: pin files

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-station#518]
Some people (such as @flyingzumwalt and @mishmosh), would like to pin files. A great feature for later 😄

**Comment by diasdavid** [comment]
I would love it too! :D The use case I was thinking was for PeerPad  https://github.com/ipfs-shipyard/peerpad/issues/90

**Comment by diasdavid** [comment]
@hacdias can you prioritize this feature?

**Comment by hacdias** [comment]
Pin files like the way pinbot pins files? Or just have a different panel where we can pin the files to have their links handy?

**Comment by flyingzumwalt** [comment]
Oh wow -- are you thinking of having station run pinning services, so I could just run station on a machine if I want to have a pinning service, and then have tools like peerpad use that as my preferred pinning service? That would be immediately useful. @hacdias read the related discussions in  ipfs-shipyard/peerpad#90 if you haven't yet. That should help you get a sense of the functionality we want.

Though, now that I think of it, we should be careful to make sure all the related functionality (pinning service, configuration, etc) is packaged as something that you can run without station -- station should just be the installer and the UI for people who don't want to use the command line. 

But still. I'm so excited to see this feature happen!

@hacdias I would be _delighted_ to spend some time with you around designing this feature in order to get the user experience right. Timing is a bit tight though -- I'll be on vacation 14-21 December.

**Comment by diasdavid** [comment]
> are you thinking of having station run pinning services, so I could just run station on a machine if I want to have a pinning service, and then have tools like peerpad use that as my preferred pinning service? That would be immediately useful

Exactly that! I knew you would like this feature, @flyingzumwalt :) 

> Pin files like the way pinbot pins files? Or just have a different panel where we can pin the files to have their links handy?

@hacdias that would be the ideal first version, a pane where users could pin hashes and add labels to them.

**Comment by hacdias** [comment]
Okay, so we'll start by doing a pane where users can pin hashes and add labels to them. Will try to start this tomorrow (or Thursday maximum) and will open a PR. After the first 'version' is completed, we can move to a pinning service.

@flyingzumwalt all help is welcome 😄

**Comment by hacdias** [comment]
Done people! Check it out!

**Comment by diasdavid** [comment]
@hacdias gifs or it didn't happen :)

**Comment by hacdias** [comment]
@diasdavid 

## Pin a new hash

[![https://gyazo.com/cc95c17262a58052d43230cb756f5c09](https://i.gyazo.com/cc95c17262a58052d43230cb756f5c09.gif)](https://gyazo.com/cc95c17262a58052d43230cb756f5c09)

# Search

[![https://gyazo.com/7e1d694d77174bd6c3493812c11318ab](https://i.gyazo.com/7e1d694d77174bd6c3493812c11318ab.gif)](https://gyazo.com/7e1d694d77174bd6c3493812c11318ab)

# Animation while pinning

[![https://gyazo.com/72e7b03963fa2eec270b2516f4f84437](https://i.gyazo.com/72e7b03963fa2eec270b2516f4f84437.gif)](https://gyazo.com/72e7b03963fa2eec270b2516f4f84437)

**Comment by diasdavid** [comment]
@hacdias wanna add as gifs all the features that Station has to the README and close this issue?

**Comment by lgierth** [comment]
Great! Suggestion: let's make these fully-qualified paths, a la /ipfs/QmFoo

**Comment by hacdias** [comment]
Will do that @lgierth @diasdavid. I'll close this afterwards.

**Comment by whyrusleeping** [comment]
Well now we need to add pin annotations support to the api, this looks really nice :)

**Comment by hacdias** [comment]
@diasdavid @lgierth @whyrusleeping  Look at this beautiful brand new README full of gifs: https://github.com/ipfs-shipyard/ipfs-station/blob/master/README.md

**Comment by jbenet** [comment]
Looking great! :)

**Comment by diasdavid** [comment]
@hacdias love it!!
